# This workflow will do a clean install of node dependencies, build the source code and update the build branch with latest changes in dist ready to be used

name: Build library to dist branch

on:
  push:
    branches: [ temporalgrid ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present

    - name: Push changes
      uses: github-actions-x/commit@v2.5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'build'
        commit-message: 'update build'
        force-add: 'true'
        name: GitHub Action
        email: action@github.com
