# This workflow will do a clean install of node dependencies, build the source code and update the build branch with latest changes in dist ready to be used

name: Node.js CI

on:
  push:
    branches: [ temporalgrid ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Update build" -a
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: build
        force: true
